### ISSUE TITLE
After updating/insertion of the entities then list become empty 

### ISSUE THREAD

**Issue by sanbond20** [pradeepgururani/AzureStorageExplorer#1]
When edit/delete the entities then gridview(table) does not visible and again when we click the query then it visible with correct entities.

**Comment by pradeepgururani** [comment]
This issue is fixed now.

**Comment by pradeepgururani** [comment]
While fixing this issue, there is some regression. Need to work on that.

**Comment by pradeepgururani** [comment]
Fixed regression.
